name: 'Helm'
description: 'Helm check and publish'
author: 'MindDoc GmbH'
inputs:
  # Github Deployment variables
  auto_merge:
    description: '
      Attempts to automatically merge the default branch into the requested ref,
      if it is behind the default branch
    '
    required: false
    default: true
  description:
    description: 'Short description of the deployment'
    required: false
    default: ''
  environment:
    description: 'Name for the target deployment environment (e.g., production, staging, qa)'
    required: false
    default: production
  payload:
    description: 'JSON payload with extra information about the deployment'
    required: false
    default: ''
  production_environment:
    description: '
      Specifies if the given environment is one that end-users directly interact with.
      Default: true when environment is production and false otherwise.'
    required: false
    default: false
  ref:
    description: 'The ref to deploy. This can be a branch, tag, or SHA'
    required: true
  required_contexts:
    description: '
      The status contexts to verify against commit status checks.
      If you omit this parameter, GitHub verifies all unique contexts before creating a deployment.
      To bypass checking entirely, pass an empty array. Defaults to all unique contexts.
    '
    required: false
  task:
    description: 'Specifies a task to execute'
    required: false
    default: deploy
  namespace:
    description: 'The kubernetes namespace to deploy to'
    required: false
    default: 'default'
  transient_environment:
    description: '
      Specifies if the given environment is specific to the deployment and will
      no longer exist at some point in the future.
    '
    required: false
    default: false
  # Github API request values
  owner:
    description: 'The organization where to deploy'
    required: false
  repo:
    description: 'The repository where to deploy'
    required: false
  token:
    description: 'The Github API token'
    required: true
runs:
  using: 'node12'
  main: 'lib/main.js'
branding:
  icon: 'cloud'
  color: 'green'
